CREATE TYPE "sexe" AS ENUM (
	'F',
	'H',
	'A'
);

CREATE TYPE "Type_Donnee" AS ENUM (
	'GPS',
	'BPM',
	'Respiration',
	'Transpiration',
	'Accelerometre'
);

CREATE TYPE "Sport" AS ENUM (
	'Musculation',
	'Course',
	'Vélo'
);

CREATE TABLE IF NOT EXISTS "user" (
	"UUID" UUID NOT NULL UNIQUE,
	"ID_User" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Nom" VARCHAR(255),
	"Prénom" VARCHAR(255),
	"Pseudo" VARCHAR(255) UNIQUE,
	"Sexe" SEXE,
	"Numero_De _Tel" VARCHAR(255),
	"Email" VARCHAR(255) UNIQUE,
	"Taille_Cm" SMALLINT CHECK("[object Object]" > 0),
	"Poids_Kg" SMALLINT CHECK("[object Object]" > 0),
	"MdP_Hash" VARCHAR(255),
	"Age" SMALLINT CHECK("[object Object]" > 0),
	"Type" VARCHAR(255) CHECK(Type IN (Fabshirt, Fablab, lambda)),
	"DateCreation" DATE NOT NULL,
	"Data" JSONB,
	PRIMARY KEY("ID_User")
);




CREATE TABLE IF NOT EXISTS "Donnée biométrique " (
	"Id_Donnee" INTEGER NOT NULL UNIQUE,
	"UUID" UUID,
	"Id_Session" INTEGER,
	"Jour" DATE,
	"Horaire" TIME,
	"Type" TYPE_DONNEE,
	"Data_Bio" JSONB,
	PRIMARY KEY("Id_Donnee")
);




CREATE TABLE IF NOT EXISTS "GPS" (
	"Id_Gps" INTEGER NOT NULL UNIQUE,
	"Altitude" DECIMAL CHECK("[object Object]" >= 0),
	"Latitude" DECIMAL,
	"Longitude" DECIMAL,
	"Time" TIMESTAMP,
	PRIMARY KEY("Id_Gps")
) INHERITS ("Donnée biométrique ");

COMMENT ON TABLE "GPS" IS 'table pour contenir les données gps';


CREATE TABLE IF NOT EXISTS "Transpiration" (
	"Id_Transpi" INTEGER NOT NULL UNIQUE,
	"Taux_Humidité" DECIMAL CHECK("[object Object]" >= 0),
	"R0" INTEGER CHECK(R0>0),
	"Unite_Transpi" VARCHAR(255),
	PRIMARY KEY("Id_Transpi")
) INHERITS ("Donnée biométrique ");

COMMENT ON TABLE "Transpiration" IS 'table pour contenir les données transpiration';


CREATE TABLE IF NOT EXISTS "BPM" (
	"Id_BPM" INTEGER NOT NULL UNIQUE,
	"Timestamp_BPM" TIMESTAMP,
	"Moyenne" SMALLINT,
	PRIMARY KEY("Id_BPM")
) INHERITS ("Donnée biométrique ");

COMMENT ON TABLE "BPM" IS 'table pour contenir les données BPM';


CREATE TABLE IF NOT EXISTS "Accelerometre" (
	"Id_Accelero" INTEGER NOT NULL UNIQUE,
	"X" DECIMAL,
	"Y" DECIMAL,
	"Z" DECIMAL,
	PRIMARY KEY("Id_Accelero")
) INHERITS ("Donnée biométrique ");

COMMENT ON TABLE "Accelerometre" IS 'table pour contenir les données imu';


CREATE TABLE IF NOT EXISTS "Respiration" (
	"Id_Respiration" INTEGER NOT NULL UNIQUE,
	"Frequence" DECIMAL CHECK("[object Object]" >= 0 AND "[object Object]" <= 20),
	"Unite_Respiration" VARCHAR(255),
	PRIMARY KEY("Id_Respiration")
) INHERITS ("Donnée biométrique ");

COMMENT ON TABLE "Respiration" IS 'table pour contenir les données du capteur respiration';


CREATE TABLE IF NOT EXISTS "Activité" (
	"Id_Activité" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"Id_Session" INTEGER,
	"Sport" SPORT,
	"Debut" TIMESTAMP,
	"Fin" TIMESTAMP,
	PRIMARY KEY("Id_Activité")
);




CREATE TABLE IF NOT EXISTS "Session" (
	"Id_Session" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"ID_User" INTEGER,
	"Debut" TIMESTAMP,
	"Fin" TIMESTAMP,
	PRIMARY KEY("Id_Session")
);




CREATE TABLE IF NOT EXISTS "Token" (
	"Id_Token" INTEGER,
	"ID_User" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"Token" VARCHAR(255),
	"Expiration" TIMESTAMP,
	PRIMARY KEY("Id_Token")
);



ALTER TABLE "Donnée biométrique "
ADD FOREIGN KEY("UUID") REFERENCES "user"("UUID")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "Activité"
ADD FOREIGN KEY("Id_Session") REFERENCES "Session"("Id_Session")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Session"
ADD FOREIGN KEY("Id_Session") REFERENCES "Donnée biométrique "("Id_Session")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("ID_User") REFERENCES "Token"("ID_User")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("ID_User") REFERENCES "Session"("ID_User")
ON UPDATE NO ACTION ON DELETE NO ACTION;